### PR TITLE
upgrade fuzzyc dependency

### PR DESCRIPTION
**Pull request by mpollmeier**

### CODE REVIEW

**Comment by mpollmeier** [comment]
@GlassAndOneHalf @ml86 the following tests are failing after upgrading fuzzyc2cpg:
```
io.shiftleft.dataflowengine.language.DataFlowTests
io.shiftleft.dataflowengine.language.FreeListDataFlowTests
io.shiftleft.dataflowengine.language.CDataFlowTests
io.shiftleft.queries.MallocMemcpyTests
io.shiftleft.queries.CopyOperations
io.shiftleft.queries.TruncationsTests
```

Can you please have a look and try to greenify it? Feel free to push directly onto this branch and merge. 
This blocks the migration to scala 2.13, because it depends on a fuzzyc2cpg release: https://github.com/ShiftLeftSecurity/codepropertygraph/pull/503

**Comment by GlassAndOneHalf** [comment]
Looks like a regression introduced in 1.1.17 of fuzzyc. Looking into fixing it now.

**Comment by GlassAndOneHalf** [comment]
This should fix it: https://github.com/ShiftLeftSecurity/fuzzyc2cpg/pull/168

**Comment by mpollmeier** [comment]
thanks @GlassAndOneHalf !

**Pull request merged**
