### PR TITLE
Added git-lfs check to project build file. (#280)

### PR DESCRIPTION
**Pull request by lifecoder**

### CODE REVIEW

**Comment by lifecoder** [comment]
> I didn't try it by uninstalling git lfs, but this looks fine.
> Is the `ProcessLogger` necessary?

@mpollmeier It is optional, but without it it just prints list of files under git-lfs to console on every build

**Comment by ml86** [comment]
@mpollmeier I think to remember that you already implemented some kind of warning mechanism like that. Am I right? If yes i think we should remove the old stuff.

**Comment by mpollmeier** [comment]
@ml86 nope I just added a how-to-install to the cs readme: https://github.com/ShiftLeftSecurity/codescience#how-to-setup-git-lfs
we could copy that to this repo - thoughts?

**Comment by ml86** [comment]
@mpollmeier If that is still required please also add this here.

**Comment by lifecoder** [comment]
@mpollmeier We already have similar instructions here on how to run/install git-lfs here just at the beginning of the README

**Pull request merged**
