### PR TITLE
revert apparently risky things

### PR DESCRIPTION
**Pull request by mpollmeier**
i don't know much about this, i was asked to revert these two, just doing as i'm told

### CODE REVIEW

**Comment by vlad-alexandru-ionescu** [comment]
CC @fabsx00 @bbrehm @ml86 FYI

**Comment by bbrehm** [comment]
@mpollmeier @vlad-alexandru-ionescu 

Does everything work with the revert, or do we need to revert https://github.com/ShiftLeftSecurity/codepropertygraph/pull/375 as well? That PR needed a version bump in 
 overflowdb (travis + sonatype woes with java8/java11 incompatibilities on overflowdb).

Can I get a short issue what was the problem, such that it can get addressed?

**Comment by mpollmeier** [comment]
@bbrehm i don't know, probably best to ask @hubertp and/or @fabsx00

**Comment by vlad-alexandru-ionescu** [comment]
As far as I understood, there wasn't a specific issue with this code. We need an urgent push to production for a certain customer and didn't want to introduce heavy changes with it, just in case. The overall tracking issue for this emergency is here: https://github.com/ShiftLeftSecurity/product/issues/3145

**Pull request merged**
