### PR TITLE
Add CONTAINED_NODE so that CONTAINED is not reused.

### PR DESCRIPTION
**Pull request by fabsx00**

### CODE REVIEW

**Comment by mpollmeier** [comment]
Hang on, this isn't just a rename, it also reverses the edge direction, right?
old: `parent --- "CONTAINS" --> child`
new: `parent <-- "CONTAINED_IN" --- child`

Is this intended? if you want to keep the directions as is, we could name them e.g. `CONTAINS_NODE`

**Comment by mpollmeier** [comment]
Also, id 31 is already in use for `BLOCK` - I'll push my proposal onto this branch.

**Comment by mpollmeier** [comment]
@fabsx00 let me know if that suits, then either you or I can update query-primitives

**Comment by fabsx00** [comment]
This works. Just tested and made adaptions accordingly. Thanks!

**Comment by mpollmeier** [comment]
Cleanup: should we close https://github.com/ShiftLeftSecurity/codescience/issues/1554 and revert https://github.com/ShiftLeftSecurity/codescience/pull/1549 then?

**Comment by fabsx00** [comment]
Good point. Let me do that in a bit.

**Comment by fabsx00** [comment]
There are still issues with https://github.com/ShiftLeftSecurity/codescience/issues/1554, so I am leaving it open. https://github.com/ShiftLeftSecurity/codescience/pull/1549 can indeed be reverted.

**Pull request merged**
