### PR TITLE
to greenify master build

### PR DESCRIPTION
**Pull request by mpollmeier**
PR build should have caught this one, I'm trying to figure out why that
didn't work

### CODE REVIEW

**Comment by mpollmeier** [comment]
strange...
https://github.com/ShiftLeftSecurity/codepropertygraph/actions/runs/6809466463/job/18515805506 was green, specifically 
grafik
 was successful. 

Yet locally it's red...
grafik


Will create another test PR...

**Comment by mpollmeier** [comment]
https://github.com/ShiftLeftSecurity/codepropertygraph/pull/1742

**Comment by mpollmeier** [comment]
ah, it's actually reproducable and I understand why: 'sbt test' automatically regenerates the sources...

**Review by max-leuthaeuser — APPROVED** [review]

**Comment by max-leuthaeuser** [comment]
Uh, nice find.

**Pull request merged**
