### PR TITLE
make queryInit explicitly return a `Query` to avoid casts

### PR DESCRIPTION
**Pull request by mpollmeier**
note: in order to reference `Query` from the macro i needed to pull it
out to another common dependency - you probably want to move it
somewhere else

### CODE REVIEW

**Review by ursachec — APPROVED** [review]
ah, nice. didn't think of moving it to a separate ~namespace~ subproject

**Comment by mpollmeier** [comment]
`s/namespace/subproject/` :)

**Review by fabsx00 — APPROVED** [review]

**Comment by mpollmeier** [comment]
@ursachec i assumed you wanted to move the query class somewhere else, or did you want to keep it where it is? I don't mind either way

**Comment by ursachec** [comment]
@mpollmeier looks ok as it is at the moment. we can move it later if necessary

**Pull request merged**
